services:
  - type: web
    name: orphanage-backend
    env: python
    rootDir: Backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      # Add your DATABASE_URL in the Render dashboard, not here for security
