"""Add home table

Revision ID: 222b6f392f93
Revises: 642bf7571bc3
Create Date: 2025-07-25 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222b6f392f93'
down_revision = '642bf7571bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('current_need', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount_contributed', sa.Float(), nullable=True),
    sa.Column('target_amount', sa.Float(), nullable=True),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home')
    # ### end Alembic commands ###
