"""Add created_at and last_login to User

Revision ID: 642bf7571bc3
Revises: e7aa34e863bf
Create Date: 2025-07-22 14:43:31.639319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642bf7571bc3'
down_revision = 'e7aa34e863bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
