"""Add image field to Home model

Revision ID: e04514f0a122
Revises: 10f12086f168
Create Date: 2025-07-29 05:37:35.398741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04514f0a122'
down_revision = '10f12086f168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homes', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
